// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoomxqwqsajaybtrwkfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvb214cXdxc2FqYXlidHJ3a2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzODg2OTYsImV4cCI6MjA2Mzk2NDY5Nn0.uCGQ3BUYuUvLmu27aLIMlGGBApRT1-29vfR9XCXyN44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);